### ISSUE TITLE
Automatic calibration function does not work reliably

### ISSUE THREAD

**Issue by jliukkonen** [ros-planning/moveit_calibration#25]
While using the Auto Calibration function, I've noticed that the Plan and Execute buttons sometimes basically do nothing. The buttons also seem to be active always although they only start to work after manually capturing at least five samples. However, even then the functionality appears to fail occasionally. I haven't been able to use the calibration tool like it is used in this video: [https://www.youtube.com/watch?v=VUZYQ23Kfas](https://www.youtube.com/watch?v=VUZYQ23Kfas)

Getting the current implementation to work reliably would be a good first step but I think the calibration workflow would be improved if user could just show the target to the camera once, and a list of poses would be generated based on that. Ideally, user would be able to scroll through that list, see a preview of each goal pose and be able to adjust them and possible remove some of them from the list. Executing would then drive the arm to each goal pose, capture an image and perform calibration based on that data once all the poses have been reached.

**Comment by JStech** [comment]
Thanks for the issue--I'll try to address where things stand currently, and at least what I envision as possible for future development.

The "auto" calibration is actually replaying previously-recorded joint states. It does not generate any new poses, currently. So yes, you need to manually take samples in order to have prerecorded poses for it to move to. The intended use case is repeating a previous calibration more than conducting a new one.

Another bug, which I think was only introduced recently (most likely by me), is that after hitting the "Plan" button, the "Execute" button moves the robot but doesn't take a sample, but then pressing the "Execute" button a second time does take a sample. So to use the prerecorded states, you basically just need to click, Plan-Execute-Execute-Plan-Execute-Execute, etc.

I agree that fully-automated pose generation for calibrating would be ideal. There are a couple practical and safety concerns, though. The safety issue is simple: moving to random poses is a great way to find objects in the scene that were left out of the collision scene. For an auto-calibration method to be safe, I think we'd want strong warnings to the user to ensure the collision scene is complete, and maybe also to limit motions to prevent joint reconfigurations and whatnot. From a practical standpoint, we would need some strategy to bootstrap a calibration from nothing: automatically-planned poses need to have the target in view, but to know whether the target will be in view for a random pose, the system needs to know the calibration. We do have the initial calibration guess, provided by the user, but I think a better approach, which would also help with the safety issue, would be to get an initial calibration with small motions in just two or three distal joints. So, we move the wrist joints by a couple degrees, verify that the target is still in view, and take a new sample. Once an initial 5 or 6 samples are acquired in this way, the initial calibration can be used to plan larger motions.

**Comment by JStech** [comment]
The bug in this issue was fixed in #56 (and it _was_ [introduced by me](https://github.com/ros-planning/moveit_calibration/commit/b3536c2710f053757f1bf26f4c53674fedc103a0)). I'll create a new issue for automated mode.
