### ISSUE TITLE
Wrong Pose-Estimate

### ISSUE THREAD

**Issue by ipa-mjp** [ros-planning/moveit_calibration#38]
Hello,

I am performing moveit calibration using ur5e robot arm and realsense camera. As far as I understand, calibration publish tf frame named with *handeye_target* after estimating pose of marker respect to *camera_color_optical_frame*. In my case, estimated pose is wrong (see image). It marked correct frame on image but tf transformation is wrong. Is any one facing same problem and solve?  I am using ROS_DISTRO as melodic.

![calibration_problem](https://user-images.githubusercontent.com/28396588/98354953-c2414880-2021-11eb-8ffe-0920844075b1.png)

**Comment by samarth-robo** [comment]
@ipa-mjp One possible cause is wrong size of the marker. Have you measured the printed size of the marker with a ruler and entered that information in the "Target" tab of the HandEyeCalibration panel?

**Comment by ipa-mjp** [comment]
Hello,
@samarth-robo Thank you for your reply. I printed marker from save marker and used that. But in order to cross check, I will measure marker size by ruler and check it.

**Comment by JStech** [comment]
If you left the measured sizes at their default values (0.2 and 0.02, I believe), that's probably the problem here--that target looks a lot smaller than ~1m wide.

When you save and print the target, the numbers in the "measured marker size (m)" and "measured separation (m)" boxes have no impact on the size of the printed target. It just generates an image with the requested pixel dimensions, and then your image software and printer actually determine the size of the printed target.

**Comment by ipa-mjp** [comment]
Hello @JStech and @samarth-robo, Thank you for you comment. A problem is from wrong measurement values  in the "measured marker size (m)" and "measured separation (m)" boxes. Now it works nicely. If any one of you want then close this issue.
