### ISSUE TITLE
Hard to always achieve satisfactory precision

### ISSUE THREAD

**Issue by remi2257** [ros-planning/moveit_calibration#41]
Hi,

_Context :_
Currently working at Niryo, I'm using your handeye calibration to get the transform of our embedded cameras on two URs !
After solving some chessboard miss detection, and set correctly all transforms, I feed 7 samples of our UR10 into Danilidis algorithm. I instantly tried to do a vision pick to check how well the calibration has been ... It was very nice. The overall error was at the most 5 mm which is great knowing that we are 40 cm above the object when taking the picture.
Then, I went to our UR5, launch the ROS stack and took 10 samples from various positions (I tried to "turn around" the chessboard). I was confident, and when I tried, results wasn't so good as it was on the UR10 even if I felt like my sample had more sense. The first time, error was +2cm and after taking new samples, error was ~1cm

_Issue Identified:_
Danilidis algorithm uses algebric Maths in order to find the optimal solution. Nevertheless, there may be missing information about some DoF in the samples, which lead to a solution that only fit the samples given, and the solution given can differ from the ground truth. Also, as AX=XB system use a pair of 2 samples, the order in which are feed the samples impact the result ! I tried that by shuffling samples order, and result can change up to 2 cm !

_Solution proposal:_
As far I can see, this algorithm can bring excellent result which a few images. Maybe you can give me some hints on "how samples should be taken to lead to optimal solution". For instance, @JStech in the issue #40 is talking about all these DoF constraints.

At the end of this issue, we can add all of these information on the Wiki or a tutorial, to help users achieve a good calibration !

Cheers :smile:

**Comment by studentWUR** [comment]
Hi,

All I am also having difficulties in getting a precise calibration.

I am using an UR5e and I want to do calibrate the position of a FRAMOS Realsense (D415).
The tool works nice, but after calibration there is an offset between the position of the robot and my depth image. For my use case this offset can not be neglected. In the images below I created a point cloud when the position of the camera with respect to the arm is left (first image) and right (second image). In other words, there is a offset in multiple locations. The problem is not caused by the inaccuracy of the urdf. Furthermore, the calibration was done using at least 10 images. 

I also tried the box dimensioner calibration tool box [(link),](https://github.com/IntelRealSense/librealsense/tree/master/wrappers/python/examples/box_dimensioner_multicam) but I got similar results as shown in the image below. My question is, how can I improve the accuracy of my calibration. Secondly, does anybody know the maximum calibration accuracy. Because I am wondering if it's is actually possible to remove the offset regardless the position of the arm. 

@remi2257 how did you calculate the overall error?

Image with the position of the arm on the left side
![left_side](https://user-images.githubusercontent.com/46886112/99090492-02c73600-25cf-11eb-9a80-7a1f4d5a8883.png)
Image with the position of the arm on the right side
![right_side](https://user-images.githubusercontent.com/46886112/99090503-05c22680-25cf-11eb-95f1-a716150a84a5.png)

**Comment by JStech** [comment]
Thanks for the detailed explanations of your accuracy issues. Getting an accurate calibration is difficult. The standard things to try are:

1. Take more samples, with more variety (rotate around all axes, capture the target in different parts of the image, etc.),
2. Try different solvers, and
3. Make sure you have accurate calibrations for the robot kinematics (via [robot_calibration](https://github.com/mikeferguson/robot_calibration), for example) and the camera intrinsics ([kalibr](https://github.com/ethz-asl/kalibr)).

Longer-term, I know it's possible to calculate the covariance of the calibrated transform, which could help determine how to take new samples. Something for the MoveIt Calibration roadmap, I guess.

**Comment by remi2257** [comment]
> @remi2257 how did you calculate the overall error?

My coworker who made the mechanical piece, plug it to the UR on SolidWorks and add the camera STL. Then, he measured the transform between ee_link & rgb_optical_frame. This result is obviously true only in theory, but it gives a good hint on which results you should achieve



Concerning your suggestions @JStech 
> 1. Take more samples, with more variety (rotate around all axes, capture the target in different parts of the image, etc.)

I already tried it, but as I say on my first message, it's kind of random? More samples do not mean better results, and which I cannot figure out, it's when a sample brings information
> 3. Make sure you have accurate calibrations for the robot kinematics (via [robot_calibration](https://github.com/mikeferguson/robot_calibration), for example) and the camera intrinsics ([kalibr](https://github.com/ethz-asl/kalibr)).

As I'm working with an UR and the camera from Intel, I'm pretty confident about these points
> Longer-term, I know it's possible to calculate the covariance of the calibrated transform, which could help determine how to take new samples. Something for the MoveIt Calibration roadmap, I guess.

I do not really know the Maths behind that, but it sounds like a solution !

I'm currently in remote due to Covid, but I will try to take a new batch of samples as soon as I get back to work, and I will keep you update about that
